# Site settings
title: Anthony Ramella | Home
description: Homepage of Anthony Ramella
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: http://tonyramella.me # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anthony Ramella
user_description:
user_title: Front-end Developer
email: aramella@protonmail.com
twitter_username: tonecodes
github_username:  tonyynot
linkedin: alramella
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-60032993-3"

# Syntax
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax

exclude: ['package.json', 'src' , 'node_modules']
